### PR TITLE
Media links

### PR DESCRIPTION
**Pull request by TheoLeanse**
@apmaros 

TODO: 
- [ ] Vertically centre the media logos. Any objections to using flexbox?
- [x] Linting 😱

### CODE REVIEW

**Comment by apmaros** [comment]
+1 LGTM Merge when you want, then you can merge to master and deploy.

**Comment by leggsimon** [comment]
RE Flexbox, depends on what browsers are using the site?

According to http://caniuse.com/#feat=flexbox IE is really our main problem

**Comment by apmaros** [comment]
@TheoLeanse its new CSS, so yeah. It seems not to be too ready for IE. 

Do you want to ship this out and then play with better CSS?

**Comment by TheoLeanse** [comment]
yep I think it's not a big deal really to have non-vertically centred logos

**Comment by leggsimon** [comment]
IMO, we should see what it looks like on IE, if it's not terrible, ship it with flexbox

**Comment by apmaros** [comment]
cool with me if you will like it on IE.

**Comment by TheoLeanse** [comment]
can we merge this to staging and make the flexbox thing a new bit of work? don't think it should block getting the press links on the site?

**Comment by TheoLeanse** [comment]
how does deployment to staging work? will these changes magically appear on http://staging-codeyourfuture.s3-website-us-west-2.amazonaws.com/ or do I need to press a button somewhere?

**Pull request merged**
